### ISSUE TITLE
What does class="no-js" do?

### ISSUE THREAD

**Issue by kodiakbrown** [docbook/xslTNG#108]
Hi, thank you for fixing [issue #100](https://github.com/docbook/xslTNG/issues/100)!  I've been trying to figure out what does class="no-js" do in the output html header?  There's no "no-js" in any of the css or javascript resources.  All of my rendered files have this header:

`<!DOCTYPE html><html xmlns="http://www.w3.org/1999/xhtml" class="no-js"><head>...`

I found some documentation on it here: https://alistapart.com/article/taking-advantage-of-html5-and-css3-with-modernizr/
It mentions to "add the class “no-js” to the html element, when Modernizr runs, it will replace that class with the class “js” which allows you to ..."

But without using modernizr, how does the class ever get replaced by the "js" class as mentioned in the link?

Thank you!

**Comment by ndw** [comment]
It's used by the theme-picker extension. It probably shouldn't be output when the theme-picker isn't being used, or the standard JavaScript should remove it.

The idea is that the page loads with the `no-js` class, then JavaScript removes it. If the document is loaded in an environment where there's no JavaScript, you can style things with no-js (to avoid having items on the page that won't work without JS).
