### ISSUE TITLE
org.xmlresolver.Resolver error

### ISSUE THREAD

**Issue by CanOfBees** [docbook/xslTNG#123]
Hi there!

When giving the ZIP distribution a trial run, I'm getting the following error:

```
bridger@ditrestle|~/bin/docbook/docbook-xslTNG-1.5.3
) java -jar libs/docbook-xslTNG-1.5.3.jar samples/article.xml -o:article.html
Transformation failed: Failed to instantiate class org.xmlresolver.Resolver (does it have a public zero-argument constructor?)
```
I'm following along in the [guide](https://xsltng.docbook.org/guide/ch02.html). 
Any suggestions for what may be going wrong? Thanks in advance!

**Comment by CanOfBees** [comment]
This is looking like a "me" issue, as this step works correctly for me on a different machine. It may be outside the scope of this issue, but I'm wondering if there's a way to progressively debug this. I'm trying to execute this command on a FreeBSD machine. Here's my JVM info:
```
bridger@ditrestle|~/bin/docbook/docbook-xslTNG-1.5.3
) java -version
openjdk version "11.0.11" 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-1)
OpenJDK 64-Bit Server VM (build 11.0.11+9-1, mixed mode)
```
Is there something I can try to run to work towards debugging this? @ndw If I'm thinking about this correctly, I might be able to stand up the xmlresolver separately and see if I can get that working. Does that sound approximately correct?

Thanks very much for any suggestions you might have.

**Comment by ndw** [comment]
Apologies for not replying sooner. I feel like I have about a thousand plates to keep spinning. There's definitely a zero argument constructor on `org.xmlresolver.Resolver` so my guess is that the "does it have" message is a red herring.

OpenJDK 11 could be relevant. I feel like I saw a backwards incompatibility there recently. Can you try with JDK 1.8?

Can you stand up and run the sample application, https://github.com/xmlresolver/sampleapp ?

**Comment by CanOfBees** [comment]
@ndw hey, please don't apologize! I should have explicitly said: "when you have some time". And you're exactly right: using OpenJDK8 seems to have addressed the problem; i.e. `article.html` is generated without a hitch.

I really appreciate your time! Thanks for the help!

**Comment by gimsieke** [comment]
You can also try more recent version such as 1.15 or 1.16. I once noticed a bug related to URIs (not related to catalog resolving though, IIRC) in 1.11 that wasn’t present in previous Java versions and that has apparently been resolved in 1.13.

**Comment by CanOfBees** [comment]
@gimsieke thanks for that suggestion. I'm giving the xmlresolver/sampleapp a spin with different (Open)JDKs and can report back.

**Comment by ndw** [comment]
I've pushed version 1.5.4 which updates the resolver dependency.
