### ISSUE TITLE
No localization data for `ar`

### ISSUE THREAD

**Issue by aowss** [docbook/xslTNG#130]
Hi,

I am new to this and might be doing something completely wrong so I apologize in advance.

I am trying to generate an html output that handles Arabic correctly ( right to left, footnote numbering, ... )

I generated a docbook file using Asciidoctor that has an `xml:lang` attribute which value is `ar`. See the attached zip file.

When i run the following command : `java -jar ./docbook-xslTNG-1.6.0/libs/docbook-xslTNG-1.6.0.jar ../فقه/أوقات\ الصلاة.xml -o:./أوقات\ الصلاة.html` i get the following error :

```
No localization data for ar
Type error on line 454 column 35 of tablecals.xsl:
  XTTE0570  A sequence of more than one item is not allowed as the value of variable $cell
  (map{(:size 7:)}, map{(:size 7:)})
at function fcals:cell on line 447 column 0 of tablecals.xsl:
     invoked by function call at https://cdn.docbook.org/release/xsltng/current/xslt/modules/tablecals.xsl#99
     invoked by xsl:for-each at https://cdn.docbook.org/release/xsltng/current/xslt/modules/tablecals.xsl#98
  In template rule with match="db:row" on line 73 of tablecals.xsl
     invoked by xsl:apply-templates at https://cdn.docbook.org/release/xsltng/current/xslt/modules/tablecals.xsl#69
  In template rule with match="element(Q{http://docbook.org/ns/docbook}tbody)" on line 66 of tablecals.xsl
     invoked by xsl:apply-templates at https://cdn.docbook.org/release/xsltng/current/xslt/modules/tablecals.xsl#62
  In template rule with match="db:tgroup" on line 52 of tablecals.xsl
     invoked by xsl:apply-templates at https://cdn.docbook.org/release/xsltng/current/xslt/modules/tablecals.xsl#43
  In template rule with match="element(Q{http://docbook.org/ns/docbook}informaltable)[tgroup]" on line 37 of tablecals.xsl
     invoked by xsl:apply-templates at https://cdn.docbook.org/release/xsltng/current/xslt/modules/sections.xsl#20
  In template rule with match="element(Q{http://docbook.org/ns/docbook}section)" on line 16 of sections.xsl
     invoked by xsl:apply-templates at https://cdn.docbook.org/release/xsltng/current/xslt/modules/components.xsl#22
  In template rule with match="element(Q{http://docbook.org/ns/docbook}article)" on line 14 of components.xsl
     invoked by xsl:apply-templates at https://cdn.docbook.org/release/xsltng/current/xslt/main.xsl#81
  In template rule with match="/" on line 72 of main.xsl
     invoked by xsl:apply-templates at https://cdn.docbook.org/release/xsltng/current/xslt/drivers.xsl#183
at template t:process on line 180 column 180 of drivers.xsl:
     invoked by xsl:call-template at https://cdn.docbook.org/release/xsltng/current/xslt/docbook.xsl#47
  In template rule with match="/" on line 37 of docbook.xsl
A sequence of more than one item is not allowed as the value of variable $cell (map{(:size 7:)}, map{(:size 7:)})
```

[‎⁨أوقات الصلاة⁩.xml.zip](https://github.com/docbook/xslTNG/files/7738621/xml.zip)

Could anyone help me figure out what is wrong ?

Thanks in advance

**Comment by ndw** [comment]
Yeah, I think this is a bug/feature. I was trying to avoid loading *all* the localization data for every transformation. There doesn't seem to be a parameter for this, which is surely a bug.

I'd be curious to know if this works: create a customization layer if you don't already have one and define `v:locales` in it:

```xml
<xsl:variable xmlns:v="http://docbook.org/ns/docbook/variables"
              name="v:locales" as="xs:string+" static="yes"
              select="('en', 'ar')"/>
```

If you can let me know if that works for you or not, I'd appreciate it. If it works, that's a short term work around. If it doesn't, l'll try to see if I can sort it out.

**Comment by aowss** [comment]
Thanks for your very prompt response.

I created the customization ( as a work-around ) and now i get the same error as above but without the `No localization data for ar` message.

I imagine this means that the customization managed to get the Arabic language loaded.

**Comment by ndw** [comment]
Your table has an overlapping structure which is not allowed. It has a structure that's effectively like this:

```
<row>
<entry align="left" valign="top" morerows="1">R1C1</entry>
<entry align="center" valign="top" namest="col_2" nameend="col_3">R1C2-C3</entry>
<entry align="left" valign="top">R1C4</entry>
<entry align="left" valign="top">R1C5</entry>
</row>
<row>
<entry align="left" valign="top">R2C2 (because R2C1 is occupied by morerows from R1C1)</entry>
<entry align="center" valign="top" namest="col_2" nameend="col_3"><simpara>R2C2-C3</simpara></entry>
…
</row>
```

When `morerows` is used, it fills the cells in the following rows. Any entries you put in that row must not include any content for the cells that have been filled from above. There's no space in the table for the content marked "R2C2" in my example above because you then explicitly put something else in R2C2 with the `namest`.

Hope that helps.

I have improved the error message for the next release. It now says "Overlapping cells in table at row _n_ for column _m_" which I expect will be a *whole* lot easier to understand. Apologies for that.

**Comment by aowss** [comment]
Sorry for wasting your time on that.

This is generated by Asciidoctor.
I will double check if that result is due to my own mistake or not.

I will then correct that and see what the result is.

**Comment by ndw** [comment]
Happy to help. You helped me find to a bug in localization support and *dramatically* improve an error message, so it's a fair exchange!
