### ISSUE TITLE
Question: epub support

### ISSUE THREAD

**Issue by aowss** [docbook/xslTNG#131]
Hi,

This is probably not the place to ask questions but i didn't know where to ask.

do xslTNG or the XSLT 2.0 version of the stylesheets support epub ?
i see an `epub` folder in the XSLT 1.0 version but i don't see the equivalent in those.

Thanks

**Comment by ndw** [comment]
No, I haven't had time to work on that yet. It's on my list, though.

**Comment by g-vidal** [comment]
If would kindly support this request  ! XSLT1 and 2 were providing this **docbook -> epub3** transform that was very usefull to build crossmedia using XML DocBook as a pivot language. _epub3.1+ accessibility 1.0 format_  provides documents that can be more easily accessed with reading tools used by disabled people. It should be a great progress if we can get back a straight forward transformation. I am not able to contribute to clean XSLTs but I can contribute for testing if needed

**Comment by bobstayton** [comment]
DocBook XSLT1 provides support for epub3 transform in the epub3 
directory, although it is probably in need of updating to meet the 
latest standards.   I have successfully produced epub3 books in the past 
with it.

Bob Stayton

**Comment by g-vidal** [comment]
Thanks for the answer ! I confirm that XSLT1 worked in the past we produced many epub3 too.  I'll check and try to point out the amendments that are needed (I found some problems with ACE validator). 
My question targets the integration of epub3 transform in xslTNG, is it scheduled ?

**Comment by ndw** [comment]
It's absolutely something I'd like to do, but there are a lot of things going on right now, so I'm not prepared to commit to a timeline. I think epub3 and some sort of solution for print output are the two big "missing pieces" in the xslTNG stylesheets and I'd like to fix both of them.

**Comment by ndw** [comment]
Implemented in 1.11.+
