### ISSUE TITLE
Document the Python/pygments/click dependencies in the build

### ISSUE THREAD

**Issue by ndw** [docbook/xslTNG#133]

**Comment by kwaxer** [comment]
It would be very helpful indeed. For example, I have installed/configured both _Python_ and _pygments_ on a Windows machine so that `pygmentize.exe` is available in the command line, but it has no effect on the output.

**Comment by ndw** [comment]
That's interesting. The dependencies I'm referring to in this issue are the build dependencies. Building [doesn't work](https://xsltng.docbook.org/guide/ch05.html) on Windows, AFAICT. And I'm not strongly motivated to work on that.

I'll see if I can reproduce the problem you're having with styling with Pygments. I thought that worked, but it may not have been tested recently. You can configure the stylesheets to use a JavaScript highlighter intead, as a workaroud.

**Comment by kwaxer** [comment]
Oh, I'm talking run-time, not about build time. I can take a look at the issue if you tell me how _pygments_ is invoked from the Java code or where to look in the source code myself.

**Comment by ndw** [comment]
I think I've fixed these problems. At least, I've moved the ball down the field.
