### ISSUE TITLE
No td/@class Attribute for entry/@role

### ISSUE THREAD

**Issue by frank-steimke** [docbook/xslTNG#154]
Hi,
while the role Attribute is transformed in a corresponding HTML class for mot elements, this does not hold for entries in CALS Table.
If have a lot of entry/@role Attributes, but no corresponding class in the generated HTML.

Is this on purpose?
xslTNG version is 1.6.2

Thanks,
Frank Steimke

**Comment by ndw** [comment]
Nope. That's almost certainly an oversight. I'll take a look asap.
