### ISSUE TITLE
Jpeg image causing Saxon Exception

### ISSUE THREAD

**Issue by wirepatch** [docbook/xslTNG#157]
Consider:

```
<informalfigure>
  <mediaobject>
    <imageobject>
      <imagedata fileref="mountain.jpg"/>
    </imageobject>
  </mediaobject>
</informalfigure>
```
The referenced image: [mountain.jpg](https://user-images.githubusercontent.com/10946447/179458502-809860f4-840d-4380-893c-b57862696138.jpg)

Current distributed Python script (based on `net.sf.saxon:Saxon-HE:11.3`)  invocation `.../docbook-xslTNG-1.7.1/bin/docbook a.xml  -xsl:.../docbook-xslTNG-1.7.1/xslt/docbook.xsl`  fails producing 666 lines of Java stack trace [err.log](https://github.com/docbook/xslTNG/files/9130038/err.log) .

**Comment by ndw** [comment]
That is very odd. The culprit is here, I think:

```
Caused by: java.lang.NullPointerException: Cannot invoke "String.replaceAll(String, String)" because "value" is null
```

I'll try to make it a priority to look at these issues this week.
