### ISSUE TITLE
Failure with multilingual modular documents

### ISSUE THREAD

**Issue by wirepatch** [docbook/xslTNG#166]
Localization partly works but fails for modular documents. The following monolithic sample transforms as expected:
```
<book version="5.1" xmlns="http://docbook.org/ns/docbook">
  <info>
    <title>Multilingual test</title>
  </info>

  <chapter>
    <title>English text</title>
    <para>Life goes on ...</para>
  </chapter>

  <chapter xml:lang="de">
    <title>Deutscher Text</title>
    <para>Das Leben geht weiter</para>
  </chapter>
</book>
```
However moving the second chapter to a module `germanChapter.xml`:
```
<chapter version="5.1" xmlns="http://docbook.org/ns/docbook"
	 xml:lang="de">
    <title>Deutscher Text</title>

    <para>Das Leben geht weiter</para>
</chapter>
```
... and using a master document: 
```
<book version="5.1" xmlns="http://docbook.org/ns/docbook"
      xmlns:xi="http://www.w3.org/2001/XInclude">
  <info>
    <title>Multilingual Xinclude test</title>
  </info>
  
  <chapter>
    <title>English text</title>
    <para>Life goes on ...</para>
  </chapter>

  <xi:include href="germanChapter.xml" xpointer="element(/1)"/>

</book>
```
... fails:
```
.../bin/docbook germanXinclude.xml  -xsl:/.../docbook.xsl 
No localization data for de 
...
```

_Originally posted by @wirepatch in https://github.com/docbook/xslTNG/issues/132#issuecomment-1191536823_

**Comment by ndw** [comment]
Yes, that's a weakness of the `()` special case. Does it work if you explicitly set `$additional-languages` to `de`?

**Comment by ndw** [comment]
It might be possible, with a memoizing function, to delay the computation until after the XIncludes have been resolved. Maybe. But I'm not sure it's worth the extra complexity.

**Comment by wirepatch** [comment]
> Yes, that's a weakness of the `()` special case. Does it work if you explicitly set `$additional-languages` to `de`?

Yes: Result as expected.

**Comment by ndw** [comment]
Okay. I think that's sufficient. I'll update the docs to make that explicit though. (So please don't close this bug yet.)

**Comment by wirepatch** [comment]
> It might be possible, with a memoizing function, to delay the computation until after the XIncludes have been resolved. Maybe. But I'm not sure it's worth the extra complexity.

I don't feel being in a position judging on that one. But next to all of my Docbook instances are modular docs and modules appear to me as kind of »natural« boundaries with respect to languages.

In my case it actually is not a problem since I'm pre-processing Docbook instances (thereby resolving Xincludes to a »flat« monolithic doc) prior to applying your stylesheets anyway.  My attempt using a modular master doc for output generation directly only happened for preliminary testing purposes.
