### ISSUE TITLE
Up key navigates off the page when in the middle of a page

### ISSUE THREAD

**Issue by ianw** [docbook/xslTNG#170]
Hi there

If you go to a book page such as

https://xsltng.docbook.org/guide/ch02.html

and move down the page (with down/pagedown), and then press the "up" key, you navigate away from the page.

I feel like what this really wants to do is only move away from the page if  the viewport is at the top of the page?

**Comment by ndw** [comment]
I decided to just remove the up arrow behavior so that it allows you to navigate up and down "normally." Thanks for letting me know!
