### ISSUE TITLE
Resource license

### ISSUE THREAD

**Issue by theGreatWhiteShark** [docbook/xslTNG#176]
Short question about the resource licensing: The original docbook XSL files featured [a custom license](https://docbook.sourceforge.net/release/xsl/current/COPYING) based on MIT. But the ones in this repo use the default MIT version. Were those files relicensed or got the MIT patch lost when migrating to Github?

**Comment by ndw** [comment]
The xslTNG stylesheets are a from-scratch rewrite, so I don't think the previous license applies. I thought choosing a straight-up MIT license would be simpler for most users. If you think I'm mistaken, or if there's some aspect of the custom license that made things easier for you, please do let me know.

**Comment by theGreatWhiteShark** [comment]
No, MIT is fine and more easy. I just wanted to make sure since I'm using your awesome stylesheets :)
