### ISSUE TITLE
Clarify in the docs the DocBook standard version supported by this project

### ISSUE THREAD

**Issue by raducoravu** [docbook/xslTNG#182]
I might be mistaken but I do not see a place in the documentation where it says what versions of the DocBook standard are supported. Does the project still support DocBook 4.x? Does it support DocBook 5.2? Is it supported completely?
Does it support the DocBook Publishers schemas as well?

**Comment by raducoravu** [comment]
@ndw thanks for clarifying this aspect. Is the DocBook Publishers schema part of the DocBok 5.2 standard?

**Comment by ndw** [comment]
Publishers is a separate spec, but it is covered by the xslTNG stylesheets. I've added that to the guide. Thanks again!

**Comment by ndw** [comment]
By the way, there's a complete report of what's supported and what isn't: https://xsltng.docbook.org/report/
