### ISSUE TITLE
Remove extra vertical bars in (unnumbered) program listings

### ISSUE THREAD

**Issue by kwaxer** [docbook/xslTNG#197]
The vertical bars `|` at the beginning of lines in program listings look like leftovers after adding proper CSS to the listings. The bars do not seem to be needed in the generated output, given the ability of CSS to declare `content` for _::before_ and _::after_ pseudo-elements. And in unnumbered listings, the generated bars overlap with the program text, making it ugly. Here is an MWE:
```
<?xml version="1.0" encoding="UTF-8"?>
<article version="5.1" xmlns="http://docbook.org/ns/docbook">
	<title>Unnumbered programlisting test</title>
	<programlisting linenumbering="unnumbered">class Foo {}</programlisting>
</article>
```
I suggest removing vertical bars from the generated output for program listings altogether. If some additional separator is still needed for numbered listings, the unconnected vertical bars are better replaced with a single border (which can be customized with CSS if needed).

**Comment by ndw** [comment]
Are you  using the included CSS files? The CSS provides a proper border and uses `display: none;` to suppress the text bars. The text bars are there for non-CSS renderings like text browsers. 

If you set the `$verbatim-number-separator` parameter to the empty string, they'll go away.

**Comment by kwaxer** [comment]
Indeed, I was using an earlier version, 1.9.0 to be precise. In 1.10.1 there are no vertical bars anymore, thank you.

However, now every line is offset from the beginning by sufficiently large whitespace (reserved for line numbers, I guess). Shouldn't elements `span.ln` disappear altogether when line numbering is not requested?

**Comment by ndw** [comment]
I *think* that's a bug in 1.10.1 that I've fixed. I'm in the middle of a fairly substantial refactor to support enerating EPUB3 files so it's a bit tangled at the moment (both on disk and in between my ears!).

I'm happy if you open another bug for that issue so that we can track it.
