### ISSUE TITLE
placeholder

### ISSUE THREAD

**Issue by olderflower** [docbook/xslTNG#204]
Greeting
Are there any placeholders in xsltNG stylesheets I can use ? If there aren't , how can I add one ? 
It looks like xslt1.0 stylesheets:
```
<!-- In these files, % with a letter is used for a placeholder: -->
<!--   %t is the current element's title -->
<!--   %s is the current element's subtitle (if applicable)-->
<!--   %n is the current element's number label-->
<!--   %p is the current element's page number (if applicable)-->
<!-- ******************************************************************** -->
```

**Comment by ndw** [comment]
What are you trying to do, exactly? Some of the configuration mechanisms have changed, but I don't think any functionality has been lost.

**Comment by olderflower** [comment]
Because there is a difference between English and Chinese. **Chapter 1** translates into Chinese should be **第 1 章**. But the label key for **Chapter** in _locale/zh_cn.xml_ is **章**, 
```
<l:gentext name="label">
... ...
      <l:tokens key="chapter">章</l:tokens>
... ...
```
When I convert the DocBook XML file to an HTML, I got the result like this **章 1**, not **第 1 章**.

So I checked the xslt1.0 stylesheet, I found there is a entry in _common/zh_cn.xml_ like this :
```
<l:template name="chapter" text="第 %n 章 %t"/>
```
Correct result can be obtained when I use the xslt1.0 stylesheet(1.79.1). So how can I get the correct result **第 1 章** in Chinese?

**Comment by ndw** [comment]
Right. I must have had a plan for that, but I admit it's looking a little broken at the moment. I'll take a look this evening.

**Comment by olderflower** [comment]
Thank you very much and I am looking forward to this exciting feature.

**Comment by ndw** [comment]
AFAICT, I just totally lost this bit of functionality. I'll fix that as quickly as I can.

**Comment by olderflower** [comment]
> I'll fix that as quickly as I can.
It's one of the best news I've heard these days. I'm looking forward to it.

**Comment by ndw** [comment]
[Progress report](https://so.nwalsh.com/2022/12/28-docbook-xsltng)

**Comment by ndw** [comment]
DocBook xslTNG 2.0.0 is now available as a pre-release. I believe it will handle Chinese correctly. Any feedback would be greatly appreciated.

**Comment by olderflower** [comment]
Thank you very much. I'll try it. If there are any problems, I'll let you know.

**Comment by ndw** [comment]
Let me know if it works, too, please :-)
