### ISSUE TITLE
Consider a DocBook validation workflow?

### ISSUE THREAD

**Issue by tomschr** [docbook/xslTNG#238]
# Problem

I really like the xslTNG project and it gives all interested users a more modern approach and layout. However, as far as I could see, this project just relies on the _transformation_ of some DocBook sources. If I'm not mistaken, it doesn't take into account a validation step.

# Proposal

Why not support an (optional) validation step before the transformation? If we already have a Docker container, this could be added through Jing and selected (or deselected) by some options.

**Comment by tomschr** [comment]
To some extend, I agree it's an "upstream" problem. I'm aware that this idea is probably better suited on a "parent" project that encompasses a more holistic view.

My (maybe naive) view was that the DocBook project could provide some sort of container where these workflow would be possible. This would also act as a form of standardization. Maybe this is something for a different project that add this functionality on top of this container.

Regarding your points 2 and 3, I guess there will be some hooks available to pass a customization layer? I'm curious how to inject your own stylesheets but use the DocBook container. I don't think I saw this in the documentation, but I could missed that.

Thanks! For the time being, I close this issue.

**Comment by ndw** [comment]
It's described in the page I linked to above, https://xsltng.docbook.org/guide/1.11.0/p_local-conventions.html and I'm reminded by that page that validate *is* part of the pre-processing that the stylesheets perform. I guess partly because I wanted to be able to validate after applying the local conventions!

**Comment by tomschr** [comment]
Thanks for the pointer and the further explanation, much appreciated! :+1:

**Comment by LdBeth** [comment]
@tomschr Just a hint if you are using Jing to validate DocBook 5.1+:
DocBook TDG [mentioned NVDL](https://tdg.docbook.org/tdg/5.2/ch03.html#ch03-validate), which can specify how to combine multiple RelaxNG/Schematron/XSD/... to validate the document.

Jing has [NVDL support contributed by oXygen](https://www.oxygenxml.com/onvdl.html) long ago but the project has never updated the documentation to reflect it.

The benefit of using NVDL is the it can use the Schematron rules for DocBook 5.1+ to check for additional constrains not handled by RelaxNG (in fact the Schematron is extracted from the DocBook RNG schema by XSLT, as currently there are not many RNG validators support embedded Schematron), and NVDL can also provide validation 
to the MathML namespace if you supplied the MathML RNG schema.

The NVDL I use to check my files as an example:
```
<rules xmlns="http://purl.oclc.org/dsdl/nvdl/ns/structure/1.0" startMode="init">
  <mode name="init">
    <namespace ns="http://docbook.org/ns/docbook">
      <validate schema="rng/docbookxi.rng" useMode="checkmml"/>
      <validate schema="sch/docbookxi.sch" useMode="allowmml"/>
    </namespace>
  </mode>
  <mode name="checkmml">
    <namespace ns="http://www.w3.org/1998/Math/MathML">
      <attach/>
      <validate schema="mathml3/mathml3.rng"/>
    </namespace>
    <namespace ns="http://www.w3.org/2001/XInclude">
      <attach/>
    </namespace>
  </mode>
  <mode name="allowmml">
    <namespace ns="http://www.w3.org/1998/Math/MathML">
      <allow/>
    </namespace>
    <namespace ns="http://www.w3.org/2001/XInclude">
      <allow/>
    </namespace>
  </mode>
</rules>
```

**Comment by tomschr** [comment]
Thank you @LdBeth for the hint! Much appreciated! :+1: Looks promising.
