### ISSUE TITLE
Problem with calling chunked docbook for XProc

### ISSUE THREAD

**Issue by xml-project** [docbook/xslTNG#251]
I call `docbook.xsl` with `p:xslt` from XProc and supply `parameters` (with SaxonHE 11.4). I get:

> Error '{http://www.w3.org/2005/xqt-errors}XTTE0570': The required item type of the value of variable $vp:chunk-output-base-uri is xs:anyURI, but the supplied expression {$chunk-output-base-uri} has item type xs:string. (docbook-xslTNG-2.0.6/xslt/modules/variable.xsl at 158/-1)

I can fix this in `variable.xsl` line 158 and 161 if I change
`<xsl:sequence select="$chunk-output-base-uri"/>`
to
`<xsl:sequence select="xs:anyURI($chunk-output-base-uri)"/>`
I think this is needed to make sure because `$chunk-output-base-uri` is an `xs:string`.
Does that make any sense?

**Comment by ndw** [comment]
I think that's a bug. I think I should just change `$chunk-output-base-uri` to a string. Will investigate

**Comment by ndw** [comment]
Okay. I see. Yes, I think your proposal is exactly correct.
