### ISSUE TITLE
some unwanted or incomplete behaviors observed

### ISSUE THREAD

**Issue by g-vidal** [docbook/xslTNG#277]
* It seems that the transformation  interjects `mp3 audio` (at least) as  not supported and triggers the  "Audio playback not supported" warning.
* epub transformations also limits the transformation of video and audio objects limiting to text only output which is not sufficient
* The `<legalnotice>` is not properly translated it should transform the text and all the information provided including small images describing the rights (Creative Commons for example)
* Due to the limitation of some browsers or readers all media formats are not systematically displayed or played `html` enables to provide more than one source but even if there are present in the docbook they are not transformed into the xhtml (maybe due to the limitations on audio and video formats)
* as docbook enables to build multimedia pages or e-pubs it should be interesting to have multiple tables : one for images, one for tables, one for audio, one for videos
* I have introduced in a docbook some accessibility information with `<meta>` tags using [schema.org](https://schema.org/CreativeWork) vocabulary recommended by [DAISY](https://daisy.org/), Docbook proposes the `aria` tags but not the `schema.org` tags wich induces errors when testing the e-pubs with `ACE`. I have not found the epub documentation on the use of accessibility terms. Could you please introduce the `schema.org` accessibility attributes and tell me where I can find the information to use them.

Thanks for your work, if needed we can help for testing

**Comment by ndw** [comment]
Thank you for these notes.

It would be useful to have a test case for the mp3 audio error described in the first bullet.

Wth respect to the second bullet, you can use profiling attributes to modify what gets transformed for epub.

An example of the input markup and the output that you'd expect for the third bullet would be useful.

I'm not sure what you mean in the fourth bullet, could you provide an example?

In the fifth bullet, are you suggesting that you'd like to have "lists of figures" subdivided into "lists of images", "lists of vidoes", etc?

Can you provide some examples of what you'd like in the sixth bullet?

(Generally speaking, if you can create a single issue for each distinct question or issue, that makes it easier to track the issues.)

**Comment by g-vidal** [comment]
Thanks @ndw for your quick and precise answers. I will close this issue and open one new, properly documented for each bullet. We are using as crash test  this [DocBook5.2 skeleton](https://xml.tremplin.ens-lyon.fr/exist/rest/db/formations/data/minimal_db5-2.xml) All our exemples are extracted from it and new ones will be integrated.
