### ISSUE TITLE
limitation to transform audio and video DocBook -> epub from #277 (moved to getting started)

### ISSUE THREAD

**Issue by g-vidal** [docbook/xslTNG#283]
My mistake sorry !
The problem observed was due to `build.gradle` configuration  from `getting started` I'll propose PR there
```shell
> Task :epub_resources
Warning: Unknown media type: media/video1.mp4
Warning: Unknown media type: media/video1.webm
Warning: Unknown media type: media/FlowerOfScotland.m4a
Warning: Unknown media type: media/FlowerOfScotland.mp3
Warning: Unknown media type: media/videos/video1.mp4
Warning: Unknown media type: media/videos/video1.webm
Warning: Unknown media type: media/audio/FlowerOfScotland.m4a
Warning: Unknown media type: media/audio/FlowerOfScotland.mp3
```

**Comment by ndw** [comment]
Yeah, that looks like an oversight.

**Comment by ndw** [comment]
Ah, right, the problem is that .mp4, .m4a, and maybe .webm can all be `audio/` or `video/` What task are you running?

**Comment by g-vidal** [comment]
Welcome to the weird world of media ! ;-) ... mp4 describes the container type; inside the container you can drop audios videos and synhronized text m4**a** is said to contain **a**udio only m4**v** **v**ideo only and mp4 video+audio+optional text various languages etc.... Unfortunately and because the container has the same structure users are not always rigorous.
You may probably safely consider m4a and mp3 as audio and mp4 and webm as videos (optionnaly rich). If a user does nor follow that rule given the fact that the containers are coherent he/she  may get an audio player ignoring images or videoplayer with black image which may help to amend the original xml.

I am using ./gradlew  publishEPUB which works if I made the modification on build.gradle.

**Comment by ndw** [comment]
I've applied the PR in the getting started project. In this project, I don't think the change needs to be made. There are no media of any of those types used here. Or am I mistaken?

**Comment by g-vidal** [comment]
You are right but for dummies of my kind that are fans of copy/paste and put audio and video in their DocBooks This change will make the copied "getting started" work with their media.... :innocent:
