### ISSUE TITLE
Enhancing figure transformation. 2/3 : adding poster image for videos

### ISSUE THREAD

**Issue by g-vidal** [docbook/xslTNG#292]
It is pleasant to choose the static image that is displayed by default for a video instead of a black window or the first image from the video. It is possible through the poster attribute of `<video>` tag in HTML and in docbook the poster type is known. It seems possible to  transform Docbook videos in something like this :
```html
<video width="800" controls="controls" poster="https://media.tremplin.ens-lyon.fr/ressources/users/EricLeJan/LivreBlanc/images/PosterDeMaVideo.png">
   <source src="https://media.tremplin.ens-lyon.fr/ressources/users/EricLeJan/LivreBlanc/videos/video1.mp4" type="video/mp4"/>
    <source src="https://media.tremplin.ens-lyon.fr/ressources/users/EricLeJan/LivreBlanc/videos/video1.webm" type="video/webm"/>
</video></span></span></span></span></span>
```
from an XML DocBook like this :
```xml
    <mediaobject>
        <videoobject>
            <videodata align="center" annotations="Video de la mise en action de l'éditeur oXygen" fileref="https://media.tremplin.ens-lyon.fr/ressources/users/EricLeJan/LivreBlanc/videos/video1.mp4" format="video/mp4" width="800" xml:id="Video_mp4">
            </videodata>
        </videoobject>
        <videoobject>
            <videodata align="center" annotations="Une video de présentation de l'éditeur en action" fileref="https://media.tremplin.ens-lyon.fr/ressources/users/EricLeJan/LivreBlanc/videos/video1.webm" format="webm" width="800" xml:id="Video1_webm">
            </videodata>
        </videoobject>
        <caption/>
    </mediaobject>
    <mediaobject role="poster">
        <imageobject role="poster">
            <imagedata align="center" annotations="Image  poster de la video" fileref="https://media.tremplin.ens-lyon.fr/ressources/users/EricLeJan/LivreBlanc/images/PosterDeMaVideo.png" format="png" role="poster" width="200" xml:id="PosterVideo1b"/>
        </imageobject>
    </mediaobject>

```

**Comment by ndw** [comment]
You could certainly write a customization layer to do that, but it doesn't feel like the right markup. Ideally you'd want just one mediaobject, I think.

I wonder if the answer here is to abuse `mediaobject` a bit. The semantics of media object are:

> This element contains a set of alternative “media objects.” Exactly one object will be selected and rendered.

I've always interpreted that as "pick one" and render it. But I think if you squinted really hard you could persuade yourself that rendering two video sources followed by an image source (from a different alternative) is still satisfying the semantics since the browser will, in fact, select and display exactly one of them.

Having a `poster` role on one of them is slightly different tag abuse.

**Comment by g-vidal** [comment]
I understand the conformity to `mediaobject`  in Docbook,  if I understand your comment you mean that if we add one more `videodata` carrying the poster image it will display it and then substitute the video as soon as it starts. I wonder if we may nee anyway to have a method to provide the `poster`  attribute of the `video`  tag which is part of the standard video tag .

Given your explanation maybe it would be acceptable to  provide another `videodata` that should carry the poster role and the fileref to the poster file. If we can infer that `videodata` might be any data contributing to the correct presentation of a video object (poster, subtitle....) and subclassing with `role` seems also acceptable from the definition _"Role contains a string used to classify or subclassify an element. While Role is a common attribute in the sense that it occurs on almost all elements, it is not part of either of the common attributes parameter entities (%common.attrib; or %idreq.common.attrib;). It is parameterized differently because it is useful to be able to subclass Role independently on different elements."_ :
```xml
               <videoobject>
                  <info>
                  <videodata align="center" annotations="Video de la mise en action de l'éditeur oXygen" fileref="https://media.tremplin.ens-lyon.fr/ressources/users/EricLeJan/LivreBlanc/videos/video1.mp4" format="video/mp4" width="800" xml:id="Video1_mp4"/>
                  <videodata align="center" annotations="Une video de présentation de l'éditeur en action" fileref="https://media.tremplin.ens-lyon.fr/ressources/users/EricLeJan/LivreBlanc/videos/video1.webm" format="webm" width="800" xml:id="Video1_webm"/>
                  <videodata role="poster" fileref="https://media.tremplin.ens-lyon.fr/ressources/users/EricLeJan/LivreBlanc/images/PosterDeMaVideo.png" format="png" width="800" xml:id="PosterVideo1"/>
```
In that case which is valid XML the transform  should convert the  :
`fileref` attribute value of `<videodata>` tag bearing the attribute `role="poster"` 
into :
value of  `poster` attribute of the `<video>` tag in the XHTML

is that acceptable @ndw  ?

**Comment by ndw** [comment]
No, I think putting a PNG on `videodata` is asking for trouble, this is how I did it: https://xsltng.docbook.org/report/xml/videoobject.003.xml

```
   <mediaobject>
     <videoobject>
       <videodata fileref="../media/spinning-top.webm"/>
       <videodata fileref="../media/spinning-top.mp4"/>
     </videoobject>
     <imageobject>
       <imagedata fileref="../media/spinning-top.png"/>
       <imagedata fileref="../media/spinning-top-poster.png" role="poster"/>
     </imageobject>
   </mediaobject>
```

**Comment by g-vidal** [comment]
Tested with 1.11.2  and 2.0.16 poster does not appear...
```html
<div class="figure formalobject" id="R_ch1_s1_3_fig1">
   <div class="mediaobject" summary="Présentation d'Oxygen en fonctionnement">
      <div class="media video">
         <span class="viewport-table" style="width:800px;">
            <span class="viewport-row">
               <span class="viewport-cell" style="text-align:center;">
                  <span>
                     <span class="viewport">
                        <video class="videoobject" controls="controls" width="800">
                           <source src="https://media.tremplin.ens-lyon.fr/ressources/users/EricLeJan/LivreBlanc/videos/video1.mp4" type="video/mp4"/>
                           <source onerror="docbook_object_fallback(parentNode)" src="https://media.tremplin.ens-lyon.fr/ressources/users/EricLeJan/LivreBlanc/videos/video1.webm" type="video/webm"/>
                        </video>
                     </span>
                  </span>
               </span>
            </span>
         </span>
      </div>
      <div class="caption">
         <p class="simpara">Légende de ma video</p>
      </div>
   </div>
   <header>
      <div class="title">Figure <span class="label">1<span class="sep">.</span>3</span><span class="sep">. </span>Titre de ma vidéo</div>
   </header>
</div>
```

**Comment by ndw** [comment]
Sorry. I just pushed that fix this morning before starting my day job. I'll push another release this evening.

**Comment by g-vidal** [comment]
Sorry I should have checked the time, no problem I'll check tomorrow and report...
