### ISSUE TITLE
Unable to use extension Fuctions from Oxygen (ClassCastException)

### ISSUE THREAD

**Issue by frank-steimke** [docbook/xslTNG#311]
Hi, 

i us the xslTNG Stylesheets Release 2.1.2 in Oxygen (recent version 25.1, Windows 10). There is a XSLT transformation scenario which calls the xslt/docbook.xsl Stylesheet. Saxon Processor is PE 11.4.
Everything is fine with the exception, that i'd like to use the extension function. Now it says _[Saxon-PE] Cannot read image properties (no extension)_

So i did two things in the Oxygen Transformation Scenario:

- Add the docbook-xslTNG2.1.2.jar as an Extension;
- Try to add the Instruction for the Saxon Initializer. Oxygen asks for the Class (implementation of net.sf.saxon.lib.Initializer). It checks the given docbook-xslTNG2.1.2.jar file, but says "No class found".
- Runnig the transformation scenario, i get an ClassCastException

`
java.lang.ClassCastException: class org.apache.xerces.parsers.XIncludeParserConfiguration cannot be cast to class org.apache.xerces.xni.parser.XMLParserConfiguration (org.apache.xerces.parsers.XIncludeParserConfiguration is in unnamed module of loader ro.sync.basic.classloader.LateDelegationClassLoader @5e517696; org.apache.xerces.xni.parser.XMLParserConfiguration is in unnamed module of loader ro.sync.basic.classloader.LateDelegationClassLoader @528931cf)`

How can i add the xslTNG extension Function to the Oxygen Scenario?

Thanks in advance,
Frank Steimke

**Comment by ndw** [comment]
I'm not sure why the initializer isn't being found. `org.docbook.xsltng.extensions.Register` is in the jar file and implements that class.

I'm not that familiar with Oxygen, but I'll try to take a look.

**Comment by ndw** [comment]
Can I infer from your subsequent issue, #312, that you figured out how to run xslTNG under Oxygen the way you needed?

**Comment by frank-steimke** [comment]
Unfortunately, no. Almost everything works, but the problem with the missing extension remains. The stylesheets cannot determine the size of the images.

**Comment by ndw** [comment]
Where Oxygen asks for the name of the class that implements the `Initializer`, did you give it `org.docbook.xsltng.extensions.Register`?

**Comment by ndw** [comment]
Although, looking at that stack trace, why this is at all related to the Xerces XInclude implementation is a bit of a mystery.

**Comment by ndw** [comment]
Right. I reproduced the problem in Oxygen and I'm stumped. I've sent an email to the Oxygen support folks. If they can tell me what I need to change, I'm happy to do it. The `Register` class works perfectly well from the command line with `-init:` so I'm stumped. Some new weirdness caused by Java modules, perhaps?

**Comment by ndw** [comment]
Oxygen says:

>The error is generated because you have a Saxon-HE-11.5.jar in the class  path and the net.sf.saxon.lib.Initializer class is loaded from that jar.  The docbook-xslTNG-2.1.2.jar has a reference in the MANIFEST.MF to the  Saxon-HE-11.5.jar. In Oxygen a different Saxon jar is used for  transformation and will not load correctly the Initializer.
>
>You need to remove the Saxon-HE-11.5.jar from the  docbook-xslTNG-2.1.2\libs\lib folder and the transformation should work.

That's an ... interesting proposition. That's going to make the stylesheets harder to use outside of Oxygen. I'll have to have a think about that one. In the meantime, if you just delete the Saxon jar file that's under libs wherever you unpacked the stylesheet distribution, I think it'll work.
