### ISSUE TITLE
Doc: Docker lets output belong to root

### ISSUE THREAD

**Issue by tomschr** [docbook/xslTNG#313]
# Situation

In section [2.4. Run with Docker](https://xsltng.docbook.org/guide/2.1.2/ch-using.html#run-with-docker) there is this paragraph and command:

```
You can use the Docker facilities for mounting directories to change what documents the script can access. For example:

$ docker run -v /tmp:/output -v /path/to/samples:/input \
         docbook-xsltng /input/article.xml chunk=index.html \
         chunk-output-base-uri=/output/
```

# Problem

I tried to follow it and here is the procedure:

1. Clone the Git repo. :wink: 
2. Create the output directory `/tmp/sample-output`.
3. Change directory to `src/main/samples/`.
4. From inside this directory, call:

        docker run -v /tmp/samples-output:/output \
                   -v $PWD:/input \
                   docbook-xsltng \
                   /input/article.xml \
                   chunk=index.html chunk-output-base-uri=/output/
5. Check the output directory:

       $ ls -l /tmp/samples-output/
       total 4
       -rw-r--r-- 1 root root 1257 Apr 27 17:45 index.html

As you can see, the output (`index.html`) belongs to root.

# Expected solution

When the docker command is called, the output should belong to the user who called it.
I'm not experienced enough with Docker so I can't provide a technical solution.
If we cannot provide a technical solution for it, the documentation should at least contain a hint about the changed ownership.

Thanks!

**Comment by ndw** [comment]
It's a fair point. I don't think I was aware of this problem when I wrote the documentation initially. It's only a problem on Linux (or, I guess, to be fair, I know that it isn't a problem on MacOS). 

The fact that Docker containers on Linux write to the local filesystem as root has been a pain in my backside on many occassions recently. I'll do something about the docs and sketch out a workaround asap.

**Comment by tomschr** [comment]
@ndw I've asked some developers about this issue. The answer was mostly "use Podman". :wink: Not sure if this would be an option.

Some other developer suggested to use `docker run --user=$(id -u) ...`. However, this lead to a Python PermissionError exception:

```
$ docker run --user=$(id -u) -v /tmp/samples-output:/output -v $PWD:/input docbook-xsltng /input/article.xml chunk=index.html chunk-output-base-uri=/output/
Traceback (most recent call last):
  File "bin/docbook", line 95, in __init__
    with open(self.config_file, "r") as depfile:
FileNotFoundError: [Errno 2] No such file or directory: '//.docbook-xsltng.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "bin/docbook", line 603, in <module>
    docbook = JavaClassRunner(sys.argv[1:])
  File "bin/docbook", line 105, in __init__
    with open(self.config_file, "w") as depfile:
PermissionError: [Errno 13] Permission denied: '//.docbook-xsltng.json'
```

**Comment by tomschr** [comment]
@ndw I've tried it with `podman` and it worked for me. Could that be a solution?

### Assumptions

* You already installed `podman` on your system.
* You cloned this repository.


### Steps

1. Create the `Dockerfile`:

        $ ./gradlew copyDocker

2. Build the container:

        $ cd build/docker/
        $ podman build -t docbook-xsltng .
        $ cd -

3. Build the example:

        $ cd src/main/samples 
        $ podman run -v /tmp/samples-output:/output -v $PWD:/input docbook-xsltng /input/article.xml chunk=index.html chunk-output-base-uri=/output/

4. Check the file:

        $ ls -l /tmp/samples-output/
        -rw-r--r-- 1 tom users 1257  3. May 13:36 index.html
