### ISSUE TITLE
para/programlisting generates p/div

### ISSUE THREAD

**Issue by tgraham-antenna** [docbook/xslTNG#319]
`div` is allowed where flow content is expected, but `p` expects only phrasing content.

Oxygen generates an error because the `div` is not allowed there, and Antenna House Formatter treats the `<div>` as closing the containing `p` then complains about the dangling `</p>` after the `</div>`.

**Comment by ndw** [comment]
If you're of a mind to put block content in paragraphs (perfectly valid in DocBook and frustratingly invalid in HTML), enable the [$unwrap-paragraphs](https://xsltng.docbook.org/guide/2.1.3/p_unwrap-paragraphs.html).

**Comment by tgraham-antenna** [comment]
`$unwrap-paragraphs` works, thank you.

**Comment by tgraham-antenna** [comment]
Sorry, but it made a `programlisting` disappear:

```
		<para>To save from having to configure the XSL formatter to use the fonts, the XSL-FO uses an AH Formatter extension for declaring local fonts inside <code>fo:declarations</code>:<programlisting language="xml"><![CDATA[<!-- https://github.com/liberationfonts/liberation-fonts/releases -->
<axf:font-face
    src="url('{$muk-xsl.dir}/liberation-fonts-ttf-2.00.5/LiberationSans-Regular.ttf')"
    font-family="Liberation Sans" />
<axf:font-face
    src="url('{$muk-xsl.dir}/liberation-fonts-ttf-2.00.5/LiberationSans-Bold.ttf')"
    font-family="Liberation Sans"
    font-weight="bold" />]]></programlisting></para>
```

**Comment by ndw** [comment]
How did that get past CI?

**Comment by ndw** [comment]
I thinks this is (re)fixed.
