### ISSUE TITLE
'page-break-inside: avoid;' on pre makes long programlisting overflow page

### ISSUE THREAD

**Issue by tgraham-antenna** [docbook/xslTNG#320]
https://github.com/docbook/xslTNG/blob/ebbbaa2e361f5aa3c5f9b4d18bb4109c55258f2e/src/main/scss/media-all.scss#L944-L950

See, e.g., page 45 of https://xsltng.docbook.org/pdf/DocBook-xslTNG-2.1.0.pdf

**Comment by ndw** [comment]
Bah humbug. Any suggestions for alternative properties that prevent breaks in short listings?

**Comment by tgraham-antenna** [comment]
Would it work to adapt the `<?dbfo-need height="2in" ?>` hackery described in http://www.sagehill.net/docbookxsl/PageBreaking.html#SoftPageBreaks?

**Comment by ndw** [comment]
Maybe. What's would you output for the "need" and how would you style it?

**Comment by tgraham-antenna** [comment]
For `programlisting` as a table, there's also `-ah-table-row-orphans`: https://www.antenna.co.jp/AHF/help/en/ahf-ext.html#axf.table-row-orphans
