### ISSUE TITLE
Undocumented dependencies

### ISSUE THREAD

**Issue by tgraham-antenna** [docbook/xslTNG#323]
Trying to run `./gradlew dist` on Linux Mint 21.1:
- Requires 'sass'
  - Installed `npm` and ran `sudo npm install -g sass`
- Had to add a symbolic link from `/usr/bin/python3` to `/usr/bin/python`
  - Could be specific to Mint/Ubuntu/Debian
- Requires Python3 `html5_parser` module
- Requires `saxonche` Python package
   - Installed `pip` and ran `pip install saxonche`
  - Was failing with:
 ```
> Task :mo_1_test_1
Traceback (most recent call last):
  File "/usr/local/src/xslTNG/src/bin/linkcheck.py", line 15, in <module>
    from saxonche import PySaxonProcessor
ModuleNotFoundError: No module named 'saxonche'
```

20 failed tests, with 18 in 'default.xspec'.

**Comment by ndw** [comment]
Ack. Right. The only time I do this is in CI, but the CI tool has all the dependencies. I'll look at this tonight as well. But in the short term, the setup is in `.github/workflows/...`
