### ISSUE TITLE
'Chapter 5. Implementation details' title doesn't break in PDF guide

### ISSUE THREAD

**Issue by tgraham-antenna** [docbook/xslTNG#324]
See https://xsltng.docbook.org/pdf/DocBook-xslTNG-2.1.0.pdf

Also occurs when formatted with Antenna House Formatter V7.3.

It is the only chapter or appendix title that overflows like this.

**Comment by ndw** [comment]
Thansk. I took out the CSS that caused program listings to overflow the page and noticed this as I was paging through to see what the consequences were. No idea what's causing it.

**Comment by tgraham-antenna** [comment]
You need AHRTS so that you don't have to eyeball PDFs looking for changes. One of the many things that I'm talking about at Markup UK 2023.

**Comment by ndw** [comment]
If you've got any ideas about why AH isn't wrapping that title?

**Comment by ndw** [comment]
I've "fixed" this by enabling hyphenation.
