### ISSUE TITLE
article/info/abstract and article/info/author lost

### ISSUE THREAD

**Issue by tgraham-antenna** [docbook/xslTNG#349]
The default stylesheets don't generate any HTML for `article/info/abstract` or `article/info/author`.

**Comment by ndw** [comment]
Trying to work out what to generate on title pages by default is kind of a fruitless task. But I suppose eliding author and abstract is a bit much. It's "easy" to change the title page template. I'll try to fix that this evening.

**Comment by ndw** [comment]
Actually, I can't reproduce that. The [expected output](https://xsltng.docbook.org/report/expected/article.001.html) for `src/test/resources/xml/article.001.xml` seems to include the authors and abtract. What am I missing?

**Comment by tgraham-antenna** [comment]
More likely that I'm missing `book` in the XPaths that I wrote about the problem.

My document is at https://github.com/tgraham-antenna/MUK-proc/blob/4362cc77f5d59bcf3eac613e9587e44d0bd5eb7c/proceedings-css.xml

When I process that using unadulterated stylesheets, I don't get the abstract. (Don't ask me why it took me this long to notice.)

**Comment by ndw** [comment]
Right, that's a `book`, not an `article`. I expect the default titlepage for `book` doesn't attempt to do the abstract. It's even harder to decide what to do about book title pages. I often end up with custom template for them.

**Comment by ndw** [comment]
That said, [this example](https://xsltng.docbook.org/report/expected/book.001.html) seems to have an abstract...

**Comment by tgraham-antenna** [comment]
I haven't got to the book title page yet.

If it was the real proceedings, the `book` would contain multiple `article`. Where do I start for making `/book/article` show more of its `info` contents?

**Comment by tgraham-antenna** [comment]
I'm getting closer.  Wasn't thinking of it as a 'title page'.

The 'Templates' section of the Guide says to use `tmp:apply-templates`, but the XSLT for the Guide doesn't use it.  When I tried to use it, I got literal `tmp:apply-templates` elements.

**Comment by ndw** [comment]
Sorry. I was away yesterday. I'll try to improve the documentation and perhaps update the defaults today.

**Comment by tgraham-antenna** [comment]
> Sorry. I was away yesterday.

Not a problem.
