### ISSUE TITLE
Hook or mode for back cover?

### ISSUE THREAD

**Issue by tgraham-antenna** [docbook/xslTNG#354]
Is there a hook or a mode for generating content for a back cover (or for any content that generated after the end of the real content)?

Currently I've copied the `*[@db-chunk]` template from `docbook-paged.xsl` to add my own hook.

**Comment by ndw** [comment]
No. That's an oversight. For a PDF, do you want the whole thing in one go: outside front cover, inside front cover, pages, inside back cover, outside back cover?

**Comment by tgraham-antenna** [comment]
I can fake what I want for now, but if you aim to support as many covery things as you can generate with the XSLT 1.0 stylesheets, then you won't disappoint too many people.

**Comment by ndw** [comment]
RIght. I haven't considered the covery things from 1.0 in a long time. I have, as a stopgap at least, added a `m:back-cover` mode. A `book` or `set` will process itself in that mode at the end of the document.
