### ISSUE TITLE
Losing text after footnote

### ISSUE THREAD

**Issue by tgraham-antenna** [docbook/xslTNG#360]
With the following paragraph, the text beginning "Graphics are..." does not appear in the HTML.

```
	<para>Papers
			typically start on an odd-numbered, right-hand page: this could just follow from
			right-hand pages being the ‘front’ of a leaf, or it could be a by-product of
			single-article reprints of papers needing to start on a right-hand page.<footnote>
				<para>Magazines and newspapers start articles as a two-page spread when it suits them, but in my limited experience, papers in journals and in conference proceedings do not start with a two-page spread.</para>
			</footnote> Graphics are typically floated to the top
			(and sometimes also to the bottom) of the page. In a two-column paper, graphics can be
			either one column wide or span both columns. Large graphics might instead be grouped at
			the back of the paper, after the references. The combination of a two-column layout plus
			floating figures generally takes fewer pages than if all text, headings, and figures
			span the width of the page.</para>
```

**Comment by tgraham-antenna** [comment]
Generates:
```
	<p>Papers
			typically start on an odd-numbered, right-hand page: this could just follow from
			right-hand pages being the ‘front’ of a leaf, or it could be a by-product of
			single-article reprints of papers needing to start on a right-hand page.<span class="footnote" id="R_article1_para2_footnote1-fnote">Magazines and newspapers start articles as a two-page spread when it suits them, but in my limited experience, papers in journals and in conference proceedings do not start with a two-page spread.</span></p>
```

**Comment by ndw** [comment]
Can you provide a sample document that demonstrates this? On its own, that paragraph seems to format just fine as HTML:

<img width="959" alt="Screenshot 2023-05-28 at 08 20 06" src="https://github.com/docbook/xslTNG/assets/36793/e3ab4752-405a-49f1-a80f-13275b41e486">

and PDF:

<img width="547" alt="Screenshot 2023-05-28 at 08 20 35" src="https://github.com/docbook/xslTNG/assets/36793/c63b16bf-e71b-47b8-96b0-2a9d1c12235a">

**Comment by tgraham-antenna** [comment]
The document is https://github.com/tgraham-antenna/MUK-proc/blob/css-proc/proceedings-css.xml, which XIncludes https://github.com/tgraham-antenna/MUK-proc/blob/css-proc/papers-2021/graham/paper.xml

If you want to regress and run Ant rather than Gradle, the command that I use with the `css-proc` branch is:
```
ant -emacs -f build-xslTNG.xml gui.single
```
This expects the `xslTNG` clone, with `gradlew zipStage` having been run, in a sibling directory to `MUK-proc`.

**Comment by ndw** [comment]
Interesting. A quick test from those sources also doesn't reproduce the problem. I can't imagine how it's related to XInclude, and yet...still investigating.

**Comment by ndw** [comment]
I've got the `css-proc` branch, but there seem to be files missing:

```
ant -emacs -f build-xslTNG.xml gui.single
Buildfile: /Volumes/Projects/docbook/MUK-proc/build-xslTNG.xml

html.prep:

single.basename:

html.single.uptodate:

html.single:

css.prep:

BUILD FAILED
/Volumes/Projects/docbook/MUK-proc/build-xslTNG.xml:151: /Volumes/Projects/docbook/MUK-proc/xsl/img does not exist.

Total time: 0 seconds
```

If I just create `xsl/img` to make that error go away, there's an error attempting to copy the `dejavu` fonts.

**Comment by ndw** [comment]
Right. This is (another) bug in unwrap-paragraphs. I have to go out for a bit, but I'll try to fix this today.

**Comment by tgraham-antenna** [comment]
There would have been a `--recurse-submodules` to clone `xsl` that I had forgotten about because I always started from an existing `MUK-proc` clone and just added/pulled the `css-proc` branch.  The instructions in `README.md` for working with the `muk2019` branch should apply to the `css-proc` branch.
