### ISSUE TITLE
'Person Name' -> 'Person Name, Orgname'?

### ISSUE THREAD

**Issue by tgraham-antenna** [docbook/xslTNG#363]
Is there a way to customise how much of `author` is shown in an `article` title page? (Other than by supplanting the XML template in `templates.xml` with custom XSLT in the `m:generate-titlepage` mode?)

Is there a mode in which the `db:author` is processed by this:
```
    <tmp:apply-templates select="db:author">
      <div class="author">
        <h3><tmp:content/></h3>
      </div>
    </tmp:apply-templates>
```
?

**Comment by ndw** [comment]
`m:titlepage` mode, I believe.

**Comment by tgraham-antenna** [comment]
Ah, I was using `m:generate-titlepage` mode and wondering why nothing was happening.
