### ISSUE TITLE
Extension function not finding 'pymentize.exe' on Windows

### ISSUE THREAD

**Issue by tgraham-antenna** [docbook/xslTNG#372]
`build.gradle` can be modified to find `pygmentize.exe` on Windows:
```
> Configure project :
Using Pygments from C:\Python311\Scripts\pygmentize.exe
```

However, I haven't seen how to modify the extension function to look for `pygmentize.exe`:
```
Failed to find pygmentize: pygmentize
Not in: C:\Python311\Scripts
...
```

**Comment by ndw** [comment]
I believe it searches the `PATH` but on Windows maybe it fails to look for `Path` :-(

Perhaps I should add an environment variable to specify it...

**Comment by tgraham-antenna** [comment]
The message shows that it's looking in the correct `C:\Python311\Scripts`. I expect that it's only matching on `pygmentize` and so not finding `pygmentize.exe`.

I don't like having to champion the Windows cause, but it's what I have to work with.

(I have to `stash` and `pop` the `.exe` change every time that I pull `build.gradle` on Windows. I don't know how to get by on Windows without it.)
