### ISSUE TITLE
Add a note about performance of syntax highlighting with Pygments

### ISSUE THREAD

**Issue by ndw** [docbook/xslTNG#38]
The note is "it's a bit grim".

I'm not sure it's a good long-term solution; suggestions for something that doesn't require spawning an external process would be helpful. Doing it in JS in the browser is fine for some use cases, but to support print, I think something that runs during the build is also necessary.

**Comment by caraya** [comment]
Prince can run Javascript and works with highlight.js for me. I don't know if running other CSS processors would work the same way.  If. you add the `--javascript` flag it should process javascript linked to from the HTML document

**Comment by ndw** [comment]
Thank you. That's good to know. I'll make support for `highlight.js` an issue.
