### ISSUE TITLE
Column width in generated HTML Table misses Pixel Unit 

### ISSUE THREAD

**Issue by frank-steimke** [docbook/xslTNG#410]
I am using xslTNG 2.1.9 Stylesheets. I have a CALS Table with two columns, with is 40mm and 120mm. I get an HTML table with a colgroup:

```
 <colgroup>
   <col style="width: 151" />
   <col style="width: 454" />
</colgroup>
```

The colum with in the Browser is not as expected (also in the PDF generated by Antenna House). Insepction in the Browser shows an error: _invalid value for width_. It is missing the unit. When i add the px unit manually, everything is fine.

Kind regards, Frank

**Comment by ndw** [comment]
Nice catch. At one point, I mentally generalized the rule "don't put `px` on 0" into "don't put `px` on numbers". Mostly I don't make that mistake any more. Mostly.
