### ISSUE TITLE
book/subtitle missing on titlepage

### ISSUE THREAD

**Issue by frank-steimke** [docbook/xslTNG#415]
I have a book with a title and a subtitle. Using the unmodified 2.1.9 stylesheets (with standard templates as distrubuted with this release) i have the title, author, editor etc. on my titlepage as expected, but the subtitle is missing.

I have checked the titlepage template for db:book and would expect the subtitle directly below the title. There is no problem, however, with chapter/subtitle.

If it is helpfull i can add a test document and result.

Greetings,
Frank

**Comment by frank-steimke** [comment]
I have checked outside of Oxygen with the `samples/article.xml` test Document in the xslTNG 2.1.9 Distribution. When i add an `subtitle` Element, it appears on the titlepage as expected. 

But when i add an `info` Element, even an empty one, the title page contains only the title, but not the subtitle. See the following snippet and the attached files.

```
<title>Sample Article</title>
<subtitle>Demonstates subtitle issue</subtitle>
<info/>
```
 Greetings, Frank

[subtitle-issue.zip](https://github.com/docbook/xslTNG/files/13039153/subtitle-issue.zip)

**Comment by ndw** [comment]
Thanks for the test case. I'll try to look at xslTNG issues this weekend.
