### ISSUE TITLE
Footnote not supported in print stylesheet

### ISSUE THREAD

**Issue by frank-steimke** [docbook/xslTNG#419]
I have checked with the simple DocBook article in the samples directory from the xslTNG Distribution. Footnotes work as expected and produce a html footer element when i use the` docbook.xsl` stylesheet. 

But when i use the `print.xsl`  stylesheet instead for the same document, no footer is produced. The footnotes content appears where the footnote element was placed in the source. This happens outside of Oxygen with Stylesheet Version 2.1.9.

Greetings, Frank

**Comment by frank-steimke** [comment]
We are using Antenna House. 

I am sure its not an matter of the CSS processor. Inspecting the generated HTML i can see that there is something wrong when we use the print.xsl stylesheet.

**Comment by ndw** [comment]
Can you provide a small sample document, the HTML that your transformation generates, and the corresponding PDF?

I just tried the `footnote.001.pdf` test document in the repository (transformed with Antenna House). The resulting HTML *does* have the footnotes embedded where they occur in the source, but that's the behavior I expect. The paged media processor is responsible for making them appear at the bottom of the page. (The XSLT transformation has no idea where page breaks will occur; leaving footnotes where they occur in the source allows the paged media processor to determine what page they should appear on.)

**Comment by frank-steimke** [comment]
Ah, i see. That means that the HTML File which has ben generated by the print.xsl stylesheet look awfully wrong in the browser, but will be rendered correct by the CSS processor.

Sorry for false alarm. We produce PDF in two steps: a) generate the HTML File, b) use the AH Formatter to produce PDF from HTML. When i saw the HTML File produced by print.xsl, with the footnotes content in the middle of the text where the footnote is placed, i was sure that something is wrong. Especially when i compared with the result of the HTML file produced from docbook.xsl.  

It did not occur to me to check this with the AH Formatter. 

Thanks for the explanation. I will close this Issue.

Greetings, Frank
