### ISSUE TITLE
Errors while running docbook.xsl

### ISSUE THREAD

**Issue by GerbenAbbink** [docbook/xslTNG#44]
When i try to run docbook.xsl i get the following errors:

In main.xsl:
Cannot find parameter-maps.xsl.
Cannot find VERSION.xsl.

Both are located in the tools directory.

**Comment by ndw** [comment]
Sorry, perhaps the instructions aren't very clear yet. If you clone the repo, you have to build the stylesheets before you can use them. Try `gradle makeXslt`. Then you'll have usable stylesheets in `build/xslt`. The sources aren't directly usable.

Apologies for the confusion.

**Comment by GerbenAbbink** [comment]
I am now following the instructions on https://xsltng.docbook.org/guide/ch05.html.

I run gradlew on Windows (./gradlew makeXslt) but i get the following error:

FAILURE: Build failed with an exception.

* Where:
Build file 'C:\ZZZ\xslTNG-main\build.gradle' line: 138

* What went wrong:
A problem occurred evaluating root project 'xslTNG-main'.
> Cannot invoke method split() on null object

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s

**Comment by ndw** [comment]
Sorry you're having trouble. You can just grab the 1.1.1 distribution in the short term, if you want to get around the build issues. I'll investigate the Windows problem asap. (This week, most likely, but probably not today.)

**Comment by GerbenAbbink** [comment]
Ok, that's working. Thank you for helping.

**Comment by ndw** [comment]
I've documented that the build isn't currently working on Windows. That's all I'm going to do for the moment.
