### ISSUE TITLE
New section in the reference manual about the use in oxygen

### ISSUE THREAD

**Issue by fsteimke** [docbook/xslTNG#452]
As long as xslTNG is not shipped with oxygen, I would appreciate a new section in the documentation for this topic. Users of oxygen have to use the nosaxon release, and have to register the xsltng jar file as an extension in transformation scenarios.

**Comment by fsteimke** [comment]
See pull request #457

**Comment by ndw** [comment]
Yes, sorry. I looked at the issues before the pull requests and hadn't realized they were paired up. Will review the PRs asap.
