### ISSUE TITLE
Better support for glossaries

### ISSUE THREAD

**Issue by fsteimke** [docbook/xslTNG#453]
This would include

- a new function `f:glossentries` which returns all _glossentries_ for a given _glossterm_ or _firstterm_, taking into account the internal documents glossary as well as external glossaries, that can be compiled and used independent from the xslTNG stylesheets. The idea is that the xslTNG Stylesheets and additional Schematron Schemas can use this function. An author can check whether there is an entry corresponding to a glossterm at the time of writing, and it would be guaranteed that there is no difference between schematron checks and the result of transformation.
- the option of simultaneous use of internal and external glossaries, so that an author is able to _overwrite_ a general glossentry from an external (shared) glossary with a more specific definition which fits better for the document he is writing. This is a requirement for the `f:glossentries` function mentioned above: it must return a sequence of all _glossentries_ for _glossterm_, and entries from the internal glossary must come first.
- a new section _"How to use (automatic) glossaries"_ in the reference manual.

Greetings, Frank

**Comment by ndw** [comment]
I merged an implementation that I modeled on yours. Comments, suggestions, and observations about where I got it wrong are most welcome :-)
