### ISSUE TITLE
Provide schematron rules for DocBook documents

### ISSUE THREAD

**Issue by fsteimke** [docbook/xslTNG#467]
Add schematron rules which help authors of DocBook documents to check

- for every `glossterm` or `firstterm` that there is exactly one element as the result of `f:glossentries ($term)`.

It depends on functions (here: `f:glossterm#1`) that are independent from the stylesheets, defined in `standalone-functions.xsl`. The idea is that authors can use theses schematron rules while authoring, in order to prevent errors that would otherwise occure when stylesheets are applied.

In next steps, this should be extended for a similar `citation` / `biblioentry/abbrev` relation, maybe _annotations_ or _abbrev / acronym_. 

The challenge is to create a mechanism that has a chance to fit into Norm`s automatic testing machinery for xslTNG. Well, I'll do my very best ...

**Comment by ndw** [comment]
I've sort of beat you to the bibliography stuff because I was eager to get a release out.
:-)

**Comment by ndw** [comment]
I think this has been resolved...
