### ISSUE TITLE
Missing python dependencies cause build failure

### ISSUE THREAD

**Issue by caraya** [docbook/xslTNG#49]
Gradle will not install Python dependencies and the lack of dependencies causes errors when compiling stylesheets. 

When trying to run `./gradlew makeXslt` or `./gradlew` I get the following error

```
> Task :makePrintCSS FAILED
Traceback (most recent call last):
  File "tools/flattencss.py", line 10, in <module>
    import click
ModuleNotFoundError: No module named 'click'

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':makePrintCSS'.
> Process 'command 'python3'' finished with non-zero exit value 1
```

Once I install click (`pip3 install -U click`), the problem goes away but having to install a Python package to get the build to work is not clear and I didn't see it documented in the guide.

**Comment by ndw** [comment]
Interesting. I guess I'll have to document that. Or rewrite `flattencss.py` so that it doesn't use click ☹️ 

(I flatten the CSS files because AH formatter doesn't understand variable declarations and a few other things in CSS.)

**Comment by ndw** [comment]
In the short term, I updated Chapter 5 to include the prerequisites.
