### ISSUE TITLE
docs website: right arrow when table of content sidebar is shown cannot be clicked

### ISSUE THREAD

**Issue by faassen** [docbook/xslTNG#490]
When you make your browser window broad enough so that you can see a chapter table of contents on the right, it becomes impossible to click the right arrow in the navigation interface at the bottom. This is likely become something in the sidebar interferes with the nav buttons. When I make the user interface more narrow I can successfully click the right arrow. I tried this in both Firefox and Chrome.

Example, make the window full width and try to click the right arrow here:

https://xsltng.docbook.org/guide/2.2.0/ch-using#epub-in-ation

**Comment by jodekirk** [comment]
This is a serious bug. When the TOC is open there is no way to click Forward/Right to the next topic. I noticed setting the z-index: 1 on the "bottom" class fixes the layers so the right arrow is clickable. 

```
<nav class="bottom" style="z-index: 1;">
```

The TOC height should be recalculated to not overlap with the bottom footer row.
