### ISSUE TITLE
Docbook 5.1 conversion using docbook-xslTNG-2.2.0.jar ignore <mediaobject> elements inside <info>

### ISSUE THREAD

**Issue by cole-meyers** [docbook/xslTNG#507]
I have a Docbook 5.1 XML file called "product_manual.xml", and I'm using docbook-xslTNG-2.2.0.jar to convert it to HTML.

I want a company logo to appear above the title of my document, but the jar file seems to be ignoring it. 

The beginning of product_manual.xml looks like this:
```
<?xml version="1.0" encoding="utf-8"?>
<!-- DocBook V4.x converted to DocBook V5.x by 10-db4to5.xsl version 1.0 -->
<book 
  xmlns="http://docbook.org/ns/docbook" 
  xmlns:xlink="http://www.w3.org/1999/xlink"
  version="5.1"
  xml:lang="en"
>


  <info>
    <mediaobject role="logo">
      <imageobject>
        <imagedata fileref="pictures/company_logo.jpg" format="JPG" />
      </imageobject>
    </mediaobject>     
    
    <title><trademark class='registered'>Product Series</trademark>: Product Name</title>
  </info>

  [...body...]

</book>
```

I convert with the command:
`java -jar <path to xslTNG>/libs/docbook-xslTNG-2.2.0.jar product_manual.xml -o:product_manual.html`

The result is an info section with a title and border, but no image. The image is totally ignored. 

If I move the `mediaobject` outside of my `info` block, in the HTML output the image appears after both the info section and the table of contents.

Why is my `mediaobject` being ignored?

How can I customize my command line (jar options) or CSS (docbook.css) to print `mediaobject` elements within <info>?

**Comment by ndw** [comment]
The stylesheets don't attempt to output everything that appears in the `info` element. You can put **a lot** of metadata in there, and may systems do. The user guide should really cover this case, thank you for raising the issue. I'll try to update the guide in the next day or two.

**Comment by cole-meyers** [comment]
Thank you for your quick reply. Glad to know I'm not seeing unexpected behavior.

Is there a workaround to achieve my goal of an image on the title/cover page? 

I notice that both the [DocBook 5.1 Reference](https://tdg.docbook.org/tdg/5.1/) and the [xslTNG Reference](https://xsltng.docbook.org/guide/2.2.0/) have title pages structured with an image on the left, and what appears to be `title` and `info` on the right. Am I to assume that these pages were not built with xslTNG or specifically docbook-xslTNG-2.2.0.jar?

**Comment by ndw** [comment]
They were both produced with these stylesheets. You just need a small customization layer to specify what and how you want titlepage elements displayed (if, as is the case here, the defaults aren't satisfactory). It's a very common use case, so common, that I've had to check twice that it isn't discussed in the documentation. A surprising oversight!

I'll try to get to it this weekend.

**Comment by cole-meyers** [comment]
Great, thank you for addressing this!

**Comment by ndw** [comment]
Here's my first attempt: https://xsltng.docbook.org/guide/2.2.0a/ch-customizing#titlepages

(Version "2.2.0a" of the guide isn't the default yet, that will be in 2.2.1 though.)

**Comment by cole-meyers** [comment]
Thank you, this is very helpful! I was able to customize my titlepage as needed.

**Comment by cole-meyers** [comment]
Marking this complete.
