### ISSUE TITLE
The key of "DANGER" in zh_cn.xml

### ISSUE THREAD

**Issue by olderflower** [docbook/xslTNG#510]
It seems that the key of "`DANGER`" in locale/zh_cn.xml has been lost. so I added the lines below into zh_cn.xml

```
      <l:token key="DANGER">危险</l:token>
      <l:token key="Danger">危险</l:token>
      <l:token key="danger">危险</l:token>
```

Is it right ?

**Comment by ndw** [comment]
that's what it looks like in the generated XSLT, it's a little different in the sources. See #511 .

And thank you!
