### ISSUE TITLE
Use of JavaScript method replaceAll on strings relies on very recent or only upcoming browser implementations

### ISSUE THREAD

**Issue by martin-honnen** [docbook/xslTNG#52]
In https://github.com/docbook/xslTNG/blob/main/src/main/web/js/annotations.js#L92 and some other places the method `replaceAll` for JavaScript strings is used. This method has only recently been implemented in some browsers like the last two Firefox releases and will be supported in the next upcoming mayor Chrome release but in the current release (84) I have it just throws an error:

> Uncaught TypeError: id.replaceAll is not a function
>     at annotations.js:55

So it might be safer or more backwards compatible to use `id = id.replace(/\./g, "\\.");`

**Comment by ndw** [comment]
Thank you, I'll do that.
