### ISSUE TITLE
How could I make a front-cover?

### ISSUE THREAD

**Issue by olderflower** [docbook/xslTNG#529]
I noticed that there is a function called `m:back-cover` which can make a back-cover. So, I wonder how I could make a front-cover which would include a few elements that I want, such as `author` , `pubdate` and so on.

**Comment by ndw** [comment]
I just recently added a section to the documentation about this: https://xsltng.docbook.org/guide/2.2.1/ch-customizing#titlepages

It's in version 2.2.1 which hasn't been released yet, but I don't think there's anything new in the stylesheets for this. Just improved documentation.
