### ISSUE TITLE
Docbook tool should propagate exit code from Saxon

### ISSUE THREAD

**Issue by frankarensmeier** [docbook/xslTNG#535]
I am playing around with Docbook NG and the docbook script included in the bin folder. It occurred to me that the exit code is always 0, no matter if Saxon was successful or not. It would be nice if the Saxon return code could be propagated in some way. Looking at the Python script, something like this might work:

```
returnCode = subprocess.call(cmd)
if (returnCode != 0):
    raise JavaClassRunnerException(f"Java process returned {returnCode}")
```

Thanks!

**Comment by ndw** [comment]
Very good idea. Thank you.

**Comment by frankarensmeier** [comment]
Maybe even better:

```
returnCode = subprocess.call(cmd)
sys.exit(returnCode)
```
