### ISSUE TITLE
xref with pagenumber does not work when using weasyprint

### ISSUE THREAD

**Issue by fsteimke** [docbook/xslTNG#546]
xref/@xrefstyle supports the %p placeholder for page numbers. Does work when using Antenna House, but not with weasyprint (you get the hashmark # instead of the targets page number).

**Comment by ndw** [comment]
The CSS for such a cross reference is:

```
.xref-pagenum {
    content: target-counter(attr(href), page);
    font-style:normal;
}
```

I think this is a weasyprint bug, not an xslTNG bug.

**Comment by ndw** [comment]
(The `#` is there so that there's some indication on the page that something didn't work.)

**Comment by fsteimke** [comment]
No, i don't think so. I'm afraid i caused the bug because i was only able to test with antenna house at that time.

CSS specification says: _"content property Applies to:  	:before and :after pseudo-elements"_. It does _not_ apply to the element itself. That's why i think that weasyprint behaves correct. 

When using the code above, which does apply the `content` property not to pseudo-elements but to the element itself

- Antenna House replaces the elements content (which is `#`) with the value from CSS `content`property (which is the targets page number). 
- weasyprint does nothing at all and displays the elements content `#`. Which seems to be correct according to the CSS Spec.

I think the solution is: an empty `a` element and
```
.xref-pagenum::after {
  content: target-counter(attr(href), page);
  font-style: normal;
}
```
I have a PR in preparation.

**Comment by ndw** [comment]
Ah. Thanks.
