### ISSUE TITLE
Persistent ToC data stored in chunk

### ISSUE THREAD

**Issue by wirepatch** [docbook/xslTNG#554]
According to [Persistent TOC data](https://xsltng.docbook.org/guide/2.4.1/ch-using.html#ptoc-data-file) defining [persistent-toc-filename](https://xsltng.docbook.org/guide/2.4.1/p_persistent-toc-filename) as empty should embed the persistent toc into each chunk rather than using JavaScript referring to a centralized external file. But I can't get this working:

1. `java -jar ... -s:../book.xml -xsl:/.../docbook.xsl chunk=index.html persistent-toc=true`
    This creates the default `persistent-toc.html` file being embedded by JavaScript.

2. Trying setting to an empty string by adding `...persistent-toc-filename='' ` fails:
    ```
    Error at xsl:apply-templates on line 24 column 55 of chunk-output.xsl:
      XTDE3365  Duplicate key in constructed map: {file:/home/goik/Downloads/tmp/...}
      In template rule with match="/" on line 20 of chunk-output.xsl
        invoked by xsl:apply-templates (tail calls omitted) at file:/home/goik/Downloads/docbook-xslTNG-2.4.1/xslt/docbook.xsl#347
    In template t:docbook on line 163 column 32 of docbook.xsl:
        invoked by xsl:call-template (tail calls omitted) at file:/home/goik/Downloads/docbook-xslTNG-2.4.1/xslt/docbook.xsl#158
    Duplicate key in constructed map: {file:/home/goik/Downloads/tmp/...}
    ```

3.  persistent-toc-filename="''" (Two single inside double quotes) , ..='()' etc. will create corresponding filenames. Unfortunately I never get an embedded TOC to be browsed as local `file:/...` rather than in a web server context.

I'm aware of the difference between an empty string vs. an empty sequence but having no clue how to define this in my (Bash shell) context

**Comment by ndw** [comment]
The way to define it is with an expression: `persistent-toc-filename="?()"` but that's tedious and very non-obvious. For the next release, an empty string will also work.
