### ISSUE TITLE
id values and chunk filenames

### ISSUE THREAD

**Issue by wirepatch** [docbook/xslTNG#558]
The legacy XSL sheets offer a parameter [use.id.as.filename](https://docbook.sourceforge.net/release/xsl/1.78.1/doc/html/use.id.as.filename.html). Carefully reading the 
[“Chunked” output](https://xsltng.docbook.org/guide/2.4.1/ch-using#chunking)  section and scanning the parameter list I was unable to find anything corresponding.

Consider:
```XML
<chapter xml:id="first">
  <title>First chapter</title>
  <para>Some text</para>
</chapter>

<chapter xml:id="second">
  <title>Second chapter</title>
  <para>More text</para>
</chapter>
```

These chapters end up in two chunks `ch01.html`  and `ch02.html` . How do I get `first.html` and `second.html` instead?

**Comment by ndw** [comment]
It's absolutley not a goal that all of the 1.0 stylesheet parameters should be reproduced in these stylesheets. That said, I've been tempted by this one myself on a few occasions. Using the PI often feels pretty redundant. And I think this is an easy fix.
