### ISSUE TITLE
How to override the unhandled.xsl match="*" template

### ISSUE THREAD

**Issue by hutchkintoot** [docbook/xslTNG#566]
I might be missing something obvious but I'm trying to add an override to the `match="*"` template in `unhandled.xsl` to have it not terminate but instead write out the illegal elements as html.

I have tried both `xsl:import` and `xsl:include` of my `custom-unhandled.xsl` in my root customization, and also tried specifying the template directly in the root customization, with and without specifying the mode `m:docbook`.

As soon as I do however, it matches all docbook elements and outputs them as "unhandled".  

Any advice on how to get this to work?

**Comment by ndw** [comment]
That is quite the conundrum. Yuck. I can't think of a workaround off the top of my head. I think the straightforward solution is to add a boolean flag to control whether it should be a fatal error or not.

**Comment by hutchkintoot** [comment]
Thanks for confirming. 

A parameter would help but I wonder if a new mode that is called from the template could offer more customization options? I.e` mode="m:unhadled"`?

**Comment by ndw** [comment]
Yes, that's a good idea.
