### ISSUE TITLE
<releaseinfo> element present in html output

### ISSUE THREAD

**Issue by johngtait** [docbook/xslTNG#76]
This DocBook code:  

`<biblioid>GCRT5021</biblioid>, <title>Track System Requirements</title>. Issue number: <edition>5</edition>. Issue date: <pubdate>December 2011</pubdate>. In-force date: <releaseinfo>March 2012</releaseinfo>. <bibliomisc>Application conditions: Part 5</bibliomisc>. </bibliomixed>`

produces &lt;releaseinfo&gt; elements visible in the html output:

`  <span class="biblioid">GCRT5021</span>, <cite class="title">Track System Requirements</cite>. Issue number: <span class="edition">5</span>. Issue date: <time class="pubdate">December 2011</time>. In-force date: <span><span style="font: monospace;                          color: yellow;                          background-color: red;                          font-weight: bold;">&lt;releaseinfo&gt;</span>March 2012<span style="font: monospace;                          color: yellow;                          background-color: red;                          font-weight: bold;">&lt;/releaseinfo&gt;</span></span>. <span class="bibliomisc">Application conditions: Part 5</span>. </p>`

**Comment by bobstayton** [comment]
In general, that output indicates that the processor found no template 
that matches the given element in that context.  I presume the context 
is inside <bibliomixed>, although the start tag for that element is 
missing in your example.

However, a template for releaseinfo does exist in mode="bibliomixed", so 
I'm not clear what going on here.  I'm not able to duplicate this 
problem with the stock DocBook stylesheets. What version of the 
stylesheets are you using?  Are you using a customization layer?  Do you 
get the same results with the stock stylesheet?

Bob Stayton
bobs@sagehill.net

**Comment by bobstayton** [comment]
Sorry, I didn't notice this was from the xslTNG project, not the 
original DocBook stylesheets.

Bob Stayton
bobs@sagehill.net
