### ISSUE TITLE
Option to generate raw HTML

### ISSUE THREAD

**Issue by tigloo** [docbook/xslTNG#82]
I'd like to use the generated output embedded in an existing webpage, so I'd like to omit the wrapping html and head tags and only output what's contained inside the body tag.

My proposal is to add a parameter "generate-html-header" defaulting to true, and only the contents of the body tag are rendered if the parameter is set to false.

(edit: mention tag by their names only because Github filtering out HTML made the request unreadable)

**Comment by ndw** [comment]
That sounds like a great idea. I'm overdue to do a little DocBook work; I'll try to get to this in the next few days.
