### ISSUE TITLE
Option to add subtitle to headline

### ISSUE THREAD

**Issue by tigloo** [docbook/xslTNG#83]
I'm trying to format legal texts and I don't have control over the source.

The text is structured so that the title text is "Article 3" and the subtitle is "Damage compensation" (for example). The currently generated TOC only includes the title element but it would be great to be able to change the headline formatting to include the subtitle.

Example: "Article 3 - Damage compensation"

**Comment by ndw** [comment]
This is already possible today with a simple customization layer that redefines the `m:toc-entry` mode for sections:

```xml
<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:db="http://docbook.org/ns/docbook"
                xmlns:f="http://docbook.org/ns/docbook/functions"
                xmlns:m="http://docbook.org/ns/docbook/modes"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns="http://www.w3.org/1999/xhtml"
                exclude-result-prefixes="db f m xs"
                version="3.0">

<xsl:import href="../../build/xslt/docbook.xsl"/>

<xsl:template match="*[db:info/db:subtitle]" mode="m:toc-entry">
  <li>
    <a href="#{f:id(.)}">
      <xsl:apply-templates select="." mode="m:headline">
        <xsl:with-param name="purpose" select="'lot'"/>
      </xsl:apply-templates>
    </a>
    <xsl:text>—</xsl:text>
    <xsl:apply-templates select="db:info/db:subtitle/node()"/>

    <xsl:apply-templates select="." mode="m:toc">
      <xsl:with-param name="nested" select="true()"/>
    </xsl:apply-templates>
  </li>
</xsl:template>

</xsl:stylesheet>
```

I'm reluctant to make it a simple boolean parameter because there would also need to be parameters for what the separator character should be (mdash in this example) and whether or not the subtitle should be part of the link or after it.

**Comment by tigloo** [comment]
Thanks, it's perfectly fine if I can control it in userspace.
