### ISSUE TITLE
Add description to documentation about how to suppress xslTNG's HTML output

### ISSUE THREAD

**Issue by tigloo** [docbook/xslTNG#84]
Together with xslTNG's HTML output I'd like to generate metadata from the same Docbook file (such as TOC in JSON format, a list of date occurrences, etc.)

When doing this, I'd like to refer to some utility function of xslTNG, most notably f:generate-id(). Ideally I would just import the main docbook.xsl stylesheet and then suppress the output for example by specifying an empty template for the root node - however, output is still produced.

Sorry for the silly request as I'm terrible at XSL.

I've tried importing only functions.xsl and shared.xsl as mentioned in the documentation, but that produced errors as well.

**Comment by ndw** [comment]
I believe this will work: in your stylesheet that imports `docbook.xsl`, create a template for `"/"` in the mode `m:docbook`:

```xml
<xsl:template match="/" mode="m:docbook" 
                        xmlns:m="http://docbook.org/ns/docbook/modes">
  <!-- you code here -->
</xsl:template>
```       
Let me know if that works for you and I'll try to document it more clearly.

**Comment by tigloo** [comment]
Ok the first error was a case of "I expect failure to declare this mode is going to be a common error." I indeed forgot to use m:docbook on the root element.

However, it still doesn't work.

Here's the template:

`
<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
    xmlns:db="http://docbook.org/ns/docbook"
    xmlns:f="http://docbook.org/ns/docbook/functions"
    xmlns:m="http://docbook.org/ns/docbook/modes"
    xmlns:mp="http://docbook.org/ns/docbook/modes/private"
    xmlns:t="http://docbook.org/ns/docbook/templates"
    xmlns:tp="http://docbook.org/ns/docbook/templates/private"
    xmlns:vp="http://docbook.org/ns/docbook/variables/private"
    xmlns:map="http://www.w3.org/2005/xpath-functions/map"
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    xmlns:h="http://www.w3.org/1999/xhtml"
    xmlns="http://www.w3.org/1999/xhtml" exclude-result-prefixes="db f h m mp t tp vp map xs" version="3.0">

    
    <xsl:import href="../xslTNG/build/xslt/docbook.xsl"/>

    <xsl:output method="text"/>

    
    <xsl:template match="/" mode="m:docbook">
        <xsl:apply-templates select="db:book" mode="TOC"/>
    </xsl:template>


    <xsl:template match="db:book" mode="TOC">
        {[
        <xsl:apply-templates mode="TOC"/>
        ]}
    </xsl:template>

    <xsl:template match="db:article|db:section|db:chapter" mode="TOC">
        {
            "ref": <xsl:text>"</xsl:text>
        <xsl:value-of select="f:generate-id(.)"/>
        <xsl:text>",</xsl:text>
            "title": <xsl:text>"</xsl:text>
        <xsl:value-of select="normalize-space(db:title)"/>
        <xsl:text>",</xsl:text>
            "subtitle": <xsl:text>"</xsl:text>
        <xsl:value-of select="normalize-space(db:subtitle)"/>
        <xsl:text>",</xsl:text>
            "items": [
        <xsl:apply-templates select="db:article|db:section|db:chapter"/>
            ],
        }
    </xsl:template>

</xsl:stylesheet>
`

The error is the following:

`
Type error on line 27 column 46 of docbook_formex_toc.xsl:
  XTTE0505  The required item type of the result of template t:process is document-node();
  the supplied value text{{[} does not match. The supplied value is a text node
  In template rule with match="element(Q{http://docbook.org/ns/docbook}book)" on line 27 of docbook_formex_toc.xsl
     invoked by xsl:apply-templates at file:/Users/till/Development/regulately-scripts/docbook_formex_toc.xsl#23
  In template rule with match="/" on line 22 of docbook_formex_toc.xsl
     invoked by xsl:apply-templates at file:/Users/till/Development/xslTNG/build/xslt/drivers.xsl#182
at template t:process on line 179 of drivers.xsl:
     invoked by xsl:call-template at file:/Users/till/Development/xslTNG/build/xslt/docbook.xsl#46
  In template rule with match="/" on line 36 of docbook.xsl
The required item type of the result of template t:process is document-node(); the supplied value text{{[} does not match. The supplied value is a text node
`

The same template works if I don't include docbook.xsl but instead copy only the code of f:generate-id().

**Comment by ndw** [comment]
Righto. Let me build a customization layer that works and document it :-)

**Comment by tigloo** [comment]
Awesome, thanks for the quick fixes!

**Comment by ndw** [comment]
You're welcome. I'm going to try to close a couple more easy ones first, but I plan to get another release out this week(ish).
