### ISSUE TITLE
Make resolve-uri() optional for objects

### ISSUE THREAD

**Issue by tigloo** [docbook/xslTNG#89]
I am referring to an image file in my Docbook file. The reference looks like this:

```
<mediaobject>
  <imageobject>
    <imagedata fileref="assets/L_2017117EN.01011402.tif.jpg"/>
  </imageobject>
</mediaobject>
```

The assets/ path is a path that's only resolvable in the final environment where the HTML file is placed, the assets are generated programmatically and retrieved via API call.

However, the tp:process-object template in objects.xsl uses resolve-uri() to create an absolute path to the asset. This turns out to be the local path on the system where I process the Docbook source:

```
<div class="mediaobject">
  <div class="imageobject">
    <div class="media">
      <img src="file:/var/folders/vc/j3pr3vw92ks_lvpknckv60t0000101/T/assets/L_2017117EN.01011402.tif.jpg"/>
    </div>
  </div>
</div>
```

Obviously, the file:/ URI is not resolvable in the target web environment where the browser interprets the HTML and then retrieves the image.

It would be great if there would be an option to retain the original URI of the media object.

**Comment by ndw** [comment]
This is supposed to be possible already by setting the `$mediaobject-input-base-uri`. In this case, if you set the input base URI to `/var/folders/vc/j3pr3vw92ks_lvpknckv60t0000101/T/`, you should get just `assets/L_2017117EN.01011402.tif.jpg` in the output.

I've struggled with this problem in lots of different ways. 

I don't object to your patch in #90 but I'll have to think about how to explain how it relates to the other options.

**Comment by tigloo** [comment]
Ah, I wasn't aware of that parameter! I'll try to use it, it's perfectly fine if it works that way. No additional parameters needed if that's the way it was intended to work.

My main use case is that I'm processing the Docbook file in a completely different folder structure than the one used to serve it to a browser, so I need control about how the asset paths are resolved.
